"""Incremental (cached) decoding for the SSM. Carries each Block's
recurrent state `h` and LocalByteConv's small causal window buffer
across calls instead of recomputing a full forward pass over the whole
context for every generated byte — the model's own generate() loop used
to do exactly that (see generation.py's history), which a benchmark
measured as ~63x slower per byte than this path at seq_len=128 context.

This is not a new model or a new approximation: it is the exact same
computation the model already does, carried step by step instead of
recomputed from scratch. Verified directly against the full forward
pass in carbide/tests/test_incremental_decode.py (matches to float32
precision, ~1e-6), the same way the chunked scan was verified against
the naive per-step reference in test_scan.py.
"""
import copy

import torch
import torch.nn.functional as F

from .mdbe import _MAX_LOOKBACK, _CLAUSE_LOOKBACK
from .layers import new_stream_state

_HISTORY_LOOKBACK = max(_MAX_LOOKBACK, _CLAUSE_LOOKBACK)


class IncrementalState:
    def __init__(self, model):
        n_layers = len(model.blocks)
        d_model = model.mdbe.base.embedding_dim
        d_state = model.blocks[0].ssm.d_state
        conv_kernel = model.local_conv.kernel_size
        self.h = [torch.zeros(1, d_model, d_state) for _ in range(n_layers)]
        self.conv_buffer = torch.zeros(1, d_model, conv_kernel - 1)
        self.byte_history = []
        d_model = model.layers.d_model if hasattr(model, "layers") else d_model
        self.pack_run = torch.zeros(d_model)
        self.pack_n = 0
        self.pack_sid = None
        self.stream = new_stream_state()  # word/sentence/Layer-3 running state

    def clone(self):
        s = IncrementalState.__new__(IncrementalState)
        s.h = [h.clone() for h in self.h]
        s.conv_buffer = self.conv_buffer.clone()
        s.byte_history = list(self.byte_history)
        s.pack_run = self.pack_run.clone()
        s.pack_n = self.pack_n
        s.pack_sid = self.pack_sid
        s.stream = copy.deepcopy(self.stream)
        return s


@torch.no_grad()
def incremental_step(model, byte_x: int, state: IncrementalState):
    """Returns (logits for the byte AFTER byte_x, updated state)."""
    bt = torch.tensor([[byte_x]])
    history = torch.tensor([state.byte_history]) if state.byte_history else None
    if hasattr(model, "layers"):
        pack = [state.pack_run, state.pack_n, state.pack_sid]
        emb, s = model.layers(bt, history=history, mode="full", pack_state=pack,
                              stream=state.stream)
        cols = s["strip"]
        state.pack_run, state.pack_n, state.pack_sid = pack[0], pack[1], pack[2]
    else:
        from .mdbe import all_constraints
        learned = model.mdbe.base(bt)
        cols = all_constraints(bt, history=history)
        emb = model.mdbe.proj(torch.cat([learned, cols], dim=-1))
    state.byte_history = (state.byte_history + [byte_x])[-(_HISTORY_LOOKBACK - 1):]

    conv_in = torch.cat([state.conv_buffer, emb.transpose(1, 2)], dim=-1)
    conv_out = model.local_conv.conv(conv_in)
    x = emb + conv_out.transpose(1, 2)
    state.conv_buffer = torch.cat([state.conv_buffer[:, :, 1:], emb.transpose(1, 2)], dim=-1)

    constraint_cols = cols

    for i, block in enumerate(model.blocks):
        h_in = block.norm(x) + block.constraint_proj(constraint_cols)
        ssm = block.ssm
        delta = F.softplus(ssm.W_delta(h_in))
        A = -torch.exp(ssm.A_log)
        a_bar = torch.exp(delta.unsqueeze(-1) * A)[:, 0]
        b_bar = (delta.unsqueeze(-1) * ssm.W_B(h_in).unsqueeze(2))[:, 0]

        h_new = a_bar * state.h[i] + b_bar
        state.h[i] = h_new

        Cx = ssm.W_C(h_in)[:, 0]
        y = (Cx.unsqueeze(1) * h_new).sum(-1)
        y = y + ssm.D * h_in[:, 0]
        x = (x[:, 0] + y).unsqueeze(1)

    logits = model.head(model.head_norm(x))[0, 0]
    return logits, state


@torch.no_grad()
def build_state(model, prefix_bytes) -> IncrementalState:
    """Feeds a prefix through the incremental path from a cold state."""
    state = IncrementalState(model)
    for b in prefix_bytes:
        _, state = incremental_step(model, b, state)
    return state
